#!/usr/bin/env bash
# Generates a production-ready .env file at the repo root.
#
# Idempotent: refuses to overwrite an existing .env. Use `--force` to
# replace one (BACKS UP first to .env.bak.<timestamp>).
#
# Reads optional defaults from the existing .env.example for documentation
# comments; the actual secret VALUES are always freshly generated.
#
# Required tools: node (for crypto.randomBytes), openssl (for sender ids).
# Both are present on standard Cloudways servers.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
FORCE=0

for arg in "$@"; do
  case "$arg" in
    --force) FORCE=1 ;;
    *) echo "[secrets] unknown arg: $arg" >&2; exit 2 ;;
  esac
done

if [[ -f "$ENV_FILE" && "$FORCE" -eq 0 ]]; then
  echo "[secrets] .env already exists at $ENV_FILE — refusing to overwrite." >&2
  echo "[secrets] Re-run with --force to back it up and regenerate." >&2
  exit 1
fi

if [[ -f "$ENV_FILE" && "$FORCE" -eq 1 ]]; then
  BACKUP="$ENV_FILE.bak.$(date -u +%Y%m%dT%H%M%SZ)"
  cp "$ENV_FILE" "$BACKUP"
  echo "[secrets] backed up existing .env to $BACKUP"
fi

# 32+ byte random secrets, hex-encoded.
hex_secret() {
  node -e "console.log(require('crypto').randomBytes($1).toString('hex'))"
}

POSTGRES_PASSWORD="$(hex_secret 24)"
REDIS_PASSWORD="$(hex_secret 24)"
SERVER_SECRET_KEY="$(hex_secret 32)"
JWT_SECRET="$(hex_secret 32)"

umask 077
cat > "$ENV_FILE" <<EOF
# Memesh production env — generated $(date -u +%Y-%m-%dT%H:%M:%SZ).
# This file MUST NOT be committed. It is gitignored by repo policy.
# Generated by scripts/cloudways/generate-secrets.sh.

# --- Runtime --------------------------------------------------------------
NODE_ENV=production
LOG_LEVEL=info

# --- Public hostname (REQUIRED for Caddy + Let's Encrypt) -----------------
# Examples: memesh.co.il, app.memesh.co.il
DOMAIN=
# Email Let's Encrypt uses for renewal-failure notifications.
LETSENCRYPT_EMAIL=

# --- Postgres --------------------------------------------------------------
POSTGRES_USER=memesh
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=memesh

# --- Redis -----------------------------------------------------------------
REDIS_PASSWORD=$REDIS_PASSWORD

# --- API secrets (generated above; 32 bytes hex = 64 chars) ----------------
SERVER_SECRET_KEY=$SERVER_SECRET_KEY
JWT_SECRET=$JWT_SECRET
JWT_ISSUER=memesh
JWT_AUDIENCE=memesh-api
JWT_CUSTOMER_AUDIENCE=memesh-customer
QR_KEY_ID=1

# --- WordPress sync (optional; leave empty to disable) ---------------------
# WP_BASE_URL=https://memesh.co.il/wp-json/wp/v2
# WP_SYNC_USER=memesh-sync
# WP_SYNC_APP_PASSWORD=

# --- SMS provider ----------------------------------------------------------
# Start with 'console' to verify the OTP flow logs to api stdout.
# When Yanai's 019 account is ready, set SMS_PROVIDER=019 and fill in the
# SMS_019_* values. SMS_019_ENDPOINT defaults to the test sandbox.
SMS_PROVIDER=console
# SMS_019_TOKEN=
# SMS_019_SOURCE=MEMESH
# SMS_019_ENDPOINT=https://019sms.co.il/api/test

# --- First-admin seed (the bootstrap script fills these from prompts) ------
SEED_ADMIN_PHONE=
SEED_ADMIN_PASSWORD=
SEED_ADMIN_FIRST_NAME=
SEED_ADMIN_LAST_NAME=

# --- Backup ----------------------------------------------------------------
BACKUP_DIR=/var/backups/memesh
BACKUP_RETENTION_DAYS=14
EOF

chmod 600 "$ENV_FILE"
echo "[secrets] wrote $ENV_FILE (mode 600)"
echo "[secrets] next: fill DOMAIN, LETSENCRYPT_EMAIL, SEED_ADMIN_* (the bootstrap script can prompt)"
