// The editable-content registry. Every entry is one admin-editable UI string:
// its stable key, Hebrew default, admin metadata, and allowed {{placeholders}}.
// Adding an editable string is a one-line addition here — no migration, since
// the DB stores only overrides keyed by these keys.
//
// Wave 2 plan 2026-07-13. Extracted surface by surface from the apps; the
// אזור אישי (customer area) comes first. Keys are stable forever — never rename
// or reuse one (the DB overrides + every t() call site depend on it).

import type { ContentEntry, ContentGroup, ContentGroupMeta } from './types';

export const CONTENT_GROUPS: ContentGroupMeta[] = [
  { id: 'customer_login', label: 'אזור אישי — התחברות' },
  { id: 'customer_general', label: 'אזור אישי — כללי וניווט' },
  { id: 'customer_cards', label: 'אזור אישי — כרטיסיות' },
  { id: 'customer_bookflow', label: 'אזור אישי — הזמנת סבב' },
  { id: 'customer_picker', label: 'אזור אישי — בחירת תאריך וסבב' },
  { id: 'customer_bookings', label: 'אזור אישי — רשימת ההזמנות' },
  { id: 'customer_booking', label: 'אזור אישי — ניהול הזמנה' },
  { id: 'customer_waitlist', label: 'אזור אישי — רשימת המתנה' },
  { id: 'customer_profile', label: 'אזור אישי — פרופיל' },
];

export const CONTENT_REGISTRY: ContentEntry[] = [
  // ── אזור אישי — כללי ──────────────────────────────────────────────
  {
    key: 'customer.nav.title',
    group: 'customer_general',
    label: 'כותרת האזור האישי',
    default: 'אזור אישי',
    kind: 'short',
  },

  // ── אזור אישי — רשימת ההזמנות (BookingsScreen) ────────────────────
  { key: 'customer.bookings.scope.upcoming', group: 'customer_bookings', label: 'לשונית — קרובות', default: 'קרובות', kind: 'short' },
  { key: 'customer.bookings.scope.past', group: 'customer_bookings', label: 'לשונית — עבר', default: 'עבר', kind: 'short' },
  { key: 'customer.bookings.scope.cancelled', group: 'customer_bookings', label: 'לשונית — בוטלו', default: 'בוטלו', kind: 'short' },
  { key: 'customer.bookings.scope.all', group: 'customer_bookings', label: 'לשונית — הכל', default: 'הכל', kind: 'short' },
  { key: 'customer.bookings.period.m1', group: 'customer_bookings', label: 'טווח — חודש אחרון', default: 'חודש אחרון', kind: 'short' },
  { key: 'customer.bookings.period.m3', group: 'customer_bookings', label: 'טווח — 3 חודשים', default: '3 חודשים', kind: 'short' },
  { key: 'customer.bookings.period.m6', group: 'customer_bookings', label: 'טווח — חצי שנה', default: 'חצי שנה', kind: 'short' },
  { key: 'customer.bookings.period.y1', group: 'customer_bookings', label: 'טווח — שנה', default: 'שנה', kind: 'short' },
  { key: 'customer.bookings.period.all', group: 'customer_bookings', label: 'טווח — הכל', default: 'הכל', kind: 'short' },
  {
    key: 'customer.bookings.empty.upcoming',
    group: 'customer_bookings',
    label: 'אין הזמנות — קרובות',
    default: 'אין הזמנות קרובות. אפשר להזמין סבב ממסך הכרטיסיות.',
    kind: 'long',
  },
  {
    key: 'customer.bookings.empty.past',
    group: 'customer_bookings',
    label: 'אין הזמנות — עבר',
    default: 'אין הזמנות שהתקיימו בטווח הזה.',
    kind: 'long',
  },
  {
    key: 'customer.bookings.empty.cancelled',
    group: 'customer_bookings',
    label: 'אין הזמנות — בוטלו',
    default: 'אין הזמנות שבוטלו.',
    kind: 'long',
  },
  {
    key: 'customer.bookings.empty.all',
    group: 'customer_bookings',
    label: 'אין הזמנות — הכל',
    default: 'עדיין אין הזמנות.',
    kind: 'long',
  },
  {
    key: 'customer.bookings.loadError',
    group: 'customer_bookings',
    label: 'שגיאת טעינת הזמנות',
    default: 'לא הצלחנו לטעון את ההזמנות. נסו שוב.',
    kind: 'long',
  },
  {
    key: 'customer.bookings.waitlistTitle',
    group: 'customer_bookings',
    label: 'כותרת רשימת המתנה',
    default: 'רשימת ההמתנה שלי',
    kind: 'short',
  },

  // ── אזור אישי — ניהול הזמנה (RoundBookingCard) ────────────────────
  // Policy copy Yanay asked for (#3a). The cancel policy uses {{hours}}; its
  // live render is wired once the configured window value reaches the app.
  {
    key: 'customer.policy.cancel',
    group: 'customer_booking',
    label: 'מדיניות ביטול',
    help: 'אפשר להשתמש ב-{{hours}} כמספר השעות שמוגדר בהגדרות הסבבים.',
    default: 'אפשר לבטל הזמנה עד {{hours}} שעות לפני תחילת המועד, והזיכוי יוחזר לאמצעי התשלום.',
    kind: 'long',
    placeholders: ['hours'],
  },
  {
    key: 'customer.policy.reschedule',
    group: 'customer_booking',
    label: 'מדיניות שינוי מועד',
    default: 'אפשר לשנות מועד עד שעת ההתחלה של ההזמנה המקורית.',
    kind: 'long',
  },
  {
    key: 'customer.booking.rescheduleButton',
    group: 'customer_booking',
    label: 'כפתור שינוי מועד',
    default: 'שנה מועד',
    kind: 'short',
  },
  {
    key: 'customer.booking.cancelButton',
    group: 'customer_booking',
    label: 'כפתור ביטול הזמנה',
    default: 'בטל הזמנה',
    kind: 'short',
  },
  {
    key: 'customer.booking.backButton',
    group: 'customer_booking',
    label: 'כפתור חזרה',
    default: 'חזרה',
    kind: 'short',
  },
  {
    key: 'customer.booking.ticketBaby',
    group: 'customer_booking',
    label: 'תווית כרטיס תינוק',
    default: 'תינוק/ת',
    kind: 'short',
  },
  {
    key: 'customer.booking.ticketChild',
    group: 'customer_booking',
    label: 'תווית כרטיס ילד',
    default: 'ילד/ה',
    kind: 'short',
  },
  {
    key: 'customer.booking.withCompanion',
    group: 'customer_booking',
    label: 'תווית מלווה נוסף',
    default: 'כולל מלווה נוסף',
    kind: 'short',
  },
  {
    key: 'customer.booking.used',
    group: 'customer_booking',
    label: 'תווית הזמנה שנוצלה',
    default: 'נוצל',
    kind: 'short',
  },
  {
    key: 'customer.booking.qrTitle',
    group: 'customer_booking',
    label: 'כותרת הברקוד',
    help: '{{label}} הוא שם הסבב.',
    default: 'ברקוד — {{label}}',
    kind: 'short',
    placeholders: ['label'],
  },
  {
    key: 'customer.booking.punchcardNote',
    group: 'customer_booking',
    label: 'הערת ניצול כניסה מהכרטיסייה',
    default:
      'כניסה אחת כבר נוצלה מהכרטיסייה עבור ההזמנה הזו והיא שמורה לך לתאריך זה. שימו לב לא לנצל את כל הכניסות לפני כן.',
    kind: 'long',
  },
  {
    key: 'customer.booking.companionPending',
    group: 'customer_booking',
    label: 'תווית מלווה ממתין לתשלום',
    default: 'מלווה נוסף — ממתין לתשלום',
    kind: 'short',
  },
  {
    key: 'customer.booking.companionPayButton',
    group: 'customer_booking',
    label: 'כפתור השלמת תשלום מלווה',
    default: 'השלמת תשלום',
    kind: 'short',
  },
  {
    key: 'customer.booking.companionPayError',
    group: 'customer_booking',
    label: 'שגיאת פתיחת תשלום מלווה',
    default: 'לא ניתן לפתוח את התשלום כרגע. נסו שוב.',
    kind: 'long',
  },
  {
    key: 'customer.booking.cancelConfirmTitle',
    group: 'customer_booking',
    label: 'כותרת אישור ביטול',
    default: 'לבטל את ההזמנה?',
    kind: 'short',
  },
  {
    key: 'customer.booking.cancelRefundPunchCompanion',
    group: 'customer_booking',
    label: 'הסבר ביטול — כרטיסייה + מלווה',
    default: 'הכניסה תוחזר לכרטיסייה שלך, והתשלום עבור המלווה הנוסף יוחזר אוטומטית.',
    kind: 'long',
  },
  {
    key: 'customer.booking.cancelRefundPunch',
    group: 'customer_booking',
    label: 'הסבר ביטול — כרטיסייה',
    default: 'הכניסה תוחזר לכרטיסייה שלך.',
    kind: 'long',
  },
  {
    key: 'customer.booking.cancelRefundPaid',
    group: 'customer_booking',
    label: 'הסבר ביטול — תשלום',
    default: 'הזיכוי יוחזר אוטומטית לאמצעי התשלום שלכם.',
    kind: 'long',
  },
  {
    key: 'customer.booking.cancelConfirmButton',
    group: 'customer_booking',
    label: 'כפתור אישור ביטול',
    default: 'כן, בטלו וזכו אותי',
    kind: 'short',
  },
  {
    key: 'customer.booking.cancelErrorTooLate',
    group: 'customer_booking',
    label: 'שגיאת ביטול — מאוחר מדי',
    default: 'כבר מאוחר מדי לבטל (אפשר עד 24 שעות לפני הסבב).',
    kind: 'long',
  },
  {
    key: 'customer.booking.cancelErrorRefundFailed',
    group: 'customer_booking',
    label: 'שגיאת ביטול — זיכוי נכשל',
    default: 'הזיכוי לא הושלם. נסו שוב או פנו אלינו.',
    kind: 'long',
  },
  {
    key: 'customer.booking.cancelErrorGeneric',
    group: 'customer_booking',
    label: 'שגיאת ביטול — כללית',
    default: 'לא ניתן לבטל כרגע. נסו שוב.',
    kind: 'long',
  },
  {
    key: 'customer.booking.swapErrorFull',
    group: 'customer_booking',
    label: 'שגיאת שינוי מועד — סבב מלא',
    default: 'הסבב התמלא. בחרו מועד אחר.',
    kind: 'long',
  },
  {
    key: 'customer.booking.swapErrorTooLate',
    group: 'customer_booking',
    label: 'שגיאת שינוי מועד — מאוחר מדי',
    default: 'כבר מאוחר מדי לשנות — אפשר עד שעת ההתחלה של ההזמנה המקורית.',
    kind: 'long',
  },
  {
    key: 'customer.booking.swapErrorGeneric',
    group: 'customer_booking',
    label: 'שגיאת שינוי מועד — כללית',
    default: 'לא ניתן לשנות כרגע. נסו שוב.',
    kind: 'long',
  },
  {
    key: 'customer.booking.pickerTitle',
    group: 'customer_booking',
    label: 'כותרת בחירת מועד',
    default: 'בחרו מועד אחר — שעה אחרת או יום אחר',
    kind: 'short',
  },
  {
    key: 'customer.booking.availabilityError',
    group: 'customer_booking',
    label: 'שגיאת טעינת זמינות',
    default: 'לא ניתן לטעון זמינות כרגע. נסו לרענן את הדף.',
    kind: 'long',
  },
  {
    key: 'customer.booking.pickerOwnDateBadge',
    group: 'customer_booking',
    label: 'סימון תאריך ההזמנה בבחירה',
    default: '(התאריך של ההזמנה)',
    kind: 'short',
  },
  {
    key: 'customer.booking.pickerEmptyClosed',
    group: 'customer_booking',
    label: 'אין מועדים — המקום סגור',
    default: 'המקום סגור בתאריך זה — בחרו יום אחר.',
    kind: 'long',
  },
  {
    key: 'customer.booking.pickerEmptyFreePlay',
    group: 'customer_booking',
    label: 'אין מועדים — כניסה חופשית',
    default: 'בתאריך זה הכניסה חופשית — אין סבבים להזמנה.',
    kind: 'long',
  },
  {
    key: 'customer.booking.pickerEmptySameDay',
    group: 'customer_booking',
    label: 'אין מועדים — אותו יום',
    default: 'אין סבב אחר פנוי ביום זה — אפשר לבחור יום אחר מהפס למעלה.',
    kind: 'long',
  },
  {
    key: 'customer.booking.pickerEmptyOtherDay',
    group: 'customer_booking',
    label: 'אין מועדים — יום אחר',
    default: 'אין סבבים פנויים ביום זה — בחרו יום אחר.',
    kind: 'long',
  },
  {
    key: 'customer.booking.statusCancelled',
    group: 'customer_booking',
    label: 'תג סטטוס — בוטל',
    default: 'בוטל',
    kind: 'short',
  },
  {
    key: 'customer.booking.rescheduleSuccess',
    group: 'customer_booking',
    label: 'הודעת הצלחה — שינוי מועד',
    default: 'המועד שונה בהצלחה! שימו לב — זה הברקוד החדש לכניסה.',
    kind: 'long',
  },

  // ── אזור אישי — התחברות (CustomerLogin) ───────────────────────────
  { key: 'customer.login.title', group: 'customer_login', label: 'כותרת מסך ההתחברות', default: 'אזור אישי', kind: 'short' },
  {
    key: 'customer.login.phonePrompt',
    group: 'customer_login',
    label: 'הנחיה — מספר טלפון',
    default: 'הזינו מספר טלפון ונשלח לכם קוד כניסה',
    kind: 'long',
  },
  { key: 'customer.login.sendCode', group: 'customer_login', label: 'כפתור — שליחת קוד', default: 'שלחו לי קוד', kind: 'short' },
  {
    key: 'customer.login.useEmail',
    group: 'customer_login',
    label: 'קישור — התחברות באימייל',
    default: 'לא קיבלתי SMS — להתחבר באימייל',
    kind: 'short',
  },
  { key: 'customer.login.enterCode', group: 'customer_login', label: 'הנחיה — הזנת קוד SMS', default: 'הזינו את הקוד שנשלח אליכם', kind: 'short' },
  {
    key: 'customer.login.codeSentTo',
    group: 'customer_login',
    label: 'הודעה — קוד נשלח',
    help: '{{target}} הוא הטלפון או האימייל.',
    default: 'קוד נשלח אל {{target}}',
    kind: 'short',
    placeholders: ['target'],
  },
  { key: 'customer.login.enter', group: 'customer_login', label: 'כפתור — כניסה', default: 'כניסה', kind: 'short' },
  {
    key: 'customer.login.resendIn',
    group: 'customer_login',
    label: 'טקסט — המתנה לשליחה חוזרת',
    help: '{{seconds}} הוא מספר השניות שנותרו.',
    default: 'שליחת קוד חדש בעוד {{seconds}} שניות',
    kind: 'short',
    placeholders: ['seconds'],
  },
  { key: 'customer.login.resend', group: 'customer_login', label: 'קישור — שליחת קוד חדש', default: 'שלחו לי קוד חדש', kind: 'short' },
  { key: 'customer.login.changePhone', group: 'customer_login', label: 'קישור — שינוי טלפון', default: 'שינוי מספר טלפון', kind: 'short' },
  {
    key: 'customer.login.emailPrompt',
    group: 'customer_login',
    label: 'הנחיה — כתובת אימייל',
    default: 'הזינו את כתובת האימייל שלכם ונשלח לכם קוד כניסה. רק אימייל שכבר רשום במערכת.',
    kind: 'long',
  },
  { key: 'customer.login.sendEmailCode', group: 'customer_login', label: 'כפתור — שליחת קוד באימייל', default: 'שלחו לי קוד באימייל', kind: 'short' },
  { key: 'customer.login.backToSms', group: 'customer_login', label: 'קישור — חזרה ל-SMS', default: 'חזרה להתחברות ב-SMS', kind: 'short' },
  { key: 'customer.login.enterEmailCode', group: 'customer_login', label: 'הנחיה — הזנת קוד אימייל', default: 'הזינו את הקוד שנשלח אליכם באימייל', kind: 'short' },
  { key: 'customer.login.changeEmail', group: 'customer_login', label: 'קישור — שינוי אימייל', default: 'שינוי כתובת האימייל', kind: 'short' },
  { key: 'customer.login.errPhone', group: 'customer_login', label: 'שגיאה — טלפון חסר', default: 'נא להזין מספר טלפון', kind: 'short' },
  { key: 'customer.login.errCode', group: 'customer_login', label: 'שגיאה — קוד חסר', default: 'נא להזין את הקוד', kind: 'short' },
  { key: 'customer.login.errEmail', group: 'customer_login', label: 'שגיאה — אימייל לא תקין', default: 'נא להזין כתובת אימייל תקינה', kind: 'short' },
  { key: 'customer.login.errEmailCode', group: 'customer_login', label: 'שגיאה — קוד אימייל חסר', default: 'נא להזין את הקוד מהאימייל', kind: 'short' },
  { key: 'customer.login.errInvalidCode', group: 'customer_login', label: 'שגיאה — קוד שגוי', default: 'הקוד אינו תקין. בדקו שוב את הספרות.', kind: 'long' },
  { key: 'customer.login.errCodeExpired', group: 'customer_login', label: 'שגיאה — קוד פג', default: 'הקוד פג תוקף. שלחו לעצמכם קוד חדש.', kind: 'long' },
  {
    key: 'customer.login.errTooMany',
    group: 'customer_login',
    label: 'שגיאה — יותר מדי ניסיונות',
    default: 'הגעתם למספר ניסיונות מירבי. נסו שוב בעוד כ-15 דקות, או שלחו קוד חדש.',
    kind: 'long',
  },
  { key: 'customer.login.errInvalidBody', group: 'customer_login', label: 'שגיאה — קלט לא תקין', default: 'הקלט אינו תקין.', kind: 'short' },
  { key: 'customer.login.err429', group: 'customer_login', label: 'שגיאה — יותר מדי בקשות', default: 'יותר מדי ניסיונות. נסו שוב בעוד דקה.', kind: 'long' },
  { key: 'customer.login.errGeneric', group: 'customer_login', label: 'שגיאה — כללית', default: 'תקלה זמנית. נסו שוב בעוד רגע.', kind: 'long' },

  // ── אזור אישי — כללי וניווט (AppShell / GiftBadge) ─────────────────
  { key: 'customer.nav.bookings', group: 'customer_general', label: 'ניווט — הזמנות', default: 'הזמנות', kind: 'short' },
  { key: 'customer.nav.cards', group: 'customer_general', label: 'ניווט — כרטיסיות', default: 'כרטיסיות', kind: 'short' },
  { key: 'customer.nav.profile', group: 'customer_general', label: 'ניווט — פרופיל', default: 'פרופיל', kind: 'short' },
  { key: 'customer.nav.signOut', group: 'customer_general', label: 'כפתור — יציאה', default: 'יציאה', kind: 'short' },
  { key: 'customer.gift.badge', group: 'customer_general', label: 'תג כרטיסיית מתנה', default: 'כרטיסיית מתנה', kind: 'short' },
  {
    key: 'customer.gift.badgeFrom',
    group: 'customer_general',
    label: 'תג מתנה — עם שם',
    help: '{{buyer}} הוא שם הקונה.',
    default: 'מתנה מ-{{buyer}}',
    kind: 'short',
    placeholders: ['buyer'],
  },

  // ── אזור אישי — כרטיסיות (CardsScreen / CollapsibleCard) ───────────
  { key: 'customer.cards.noExpiry', group: 'customer_cards', label: 'כרטיסייה — ללא תפוגה', default: 'ללא תפוגה', kind: 'short' },
  {
    key: 'customer.cards.expiryUntil',
    group: 'customer_cards',
    label: 'כרטיסייה — תוקף עד',
    help: '{{date}} הוא תאריך התפוגה.',
    default: 'תוקף עד {{date}}',
    kind: 'short',
    placeholders: ['date'],
  },
  { key: 'customer.cards.giftCard', group: 'customer_cards', label: 'כותרת — כרטיסיית מתנה', default: 'כרטיסייה במתנה', kind: 'short' },
  { key: 'customer.cards.card', group: 'customer_cards', label: 'כותרת — כרטיסייה', default: 'כרטיסייה', kind: 'short' },
  {
    key: 'customer.cards.remaining',
    group: 'customer_cards',
    label: 'כרטיסייה — כניסות שנותרו',
    help: '{{remaining}} כניסות שנותרו, {{total}} סך הכל, {{expiry}} טקסט התוקף.',
    default: 'נותרו {{remaining}} מתוך {{total}} כניסות · {{expiry}}',
    kind: 'long',
    placeholders: ['remaining', 'total', 'expiry'],
  },
  {
    key: 'customer.cards.qrTitle',
    group: 'customer_cards',
    label: 'כותרת קוד QR',
    help: '{{serial}} הוא מספר הכרטיסייה.',
    default: 'קוד QR — {{serial}}',
    kind: 'short',
    placeholders: ['serial'],
  },
  { key: 'customer.cards.upcomingFromCard', group: 'customer_cards', label: 'הערה — הזמנה עתידית מהכרטיסייה', default: 'יש לך הזמנה עתידית מכרטיסייה זו ·', kind: 'long' },
  { key: 'customer.cards.loadError', group: 'customer_cards', label: 'שגיאת טעינת כרטיסיות', default: 'לא הצלחנו לטעון את הכרטיסיות. רעננו את הדף.', kind: 'long' },
  { key: 'customer.cards.empty', group: 'customer_cards', label: 'אין כרטיסיות', default: 'אין כרטיסיות פעילות.', kind: 'short' },

  // ── אזור אישי — הזמנת סבב (PunchRoundBooking) ──────────────────────
  { key: 'customer.bookflow.title', group: 'customer_bookflow', label: 'כותרת — הזמנת סבב', default: 'הזמנת כניסה לסבב', kind: 'short' },
  { key: 'customer.bookflow.close', group: 'customer_bookflow', label: 'כפתור — סגירה', default: 'סגירה', kind: 'short' },
  { key: 'customer.bookflow.spaceAvailable', group: 'customer_bookflow', label: 'הודעה — יש מקום', default: 'יש מקום פנוי — אפשר להזמין ישירות.', kind: 'long' },
  { key: 'customer.bookflow.joinError', group: 'customer_bookflow', label: 'שגיאה — הצטרפות לרשימה', default: 'לא ניתן להצטרף לרשימה כרגע.', kind: 'long' },
  {
    key: 'customer.bookflow.joinedWaitlist',
    group: 'customer_bookflow',
    label: 'הודעה — נרשמת לרשימת המתנה',
    help: '{{time}} שעת הסבב.',
    default: 'נרשמת לרשימת ההמתנה לסבב {{time}}. נודיע לך אם יתפנה מקום.',
    kind: 'long',
    placeholders: ['time'],
  },
  { key: 'customer.bookflow.errNotEnoughSpace', group: 'customer_bookflow', label: 'שגיאה — אין מספיק מקום', default: 'אין מספיק מקומות פנויים בסבב. בחרו זמן אחר.', kind: 'long' },
  { key: 'customer.bookflow.errNotEnoughEntries', group: 'customer_bookflow', label: 'שגיאה — אין מספיק כניסות', default: 'לא נותרו מספיק כניסות בכרטיסייה.', kind: 'long' },
  { key: 'customer.bookflow.errNoEntries', group: 'customer_bookflow', label: 'שגיאה — אין כניסות', default: 'לכרטיסייה לא נותרו כניסות.', kind: 'long' },
  { key: 'customer.bookflow.errCardExpired', group: 'customer_bookflow', label: 'שגיאה — כרטיסייה פגה', default: 'הכרטיסייה פגה.', kind: 'short' },
  { key: 'customer.bookflow.errGeneric', group: 'customer_bookflow', label: 'שגיאה — כללית', default: 'לא ניתן להזמין כרגע. נסו שוב.', kind: 'long' },
  {
    key: 'customer.bookflow.companionPendingNote',
    group: 'customer_bookflow',
    label: 'הודעה — תשלום מלווה לא הושלם',
    default: 'ההזמנה נקלטה, אבל התשלום עבור המלווה הנוסף לא הושלם. אפשר להשלים אותו מכרטיס ההזמנה למטה.',
    kind: 'long',
  },
  {
    key: 'customer.bookflow.successMulti',
    group: 'customer_bookflow',
    label: 'הצלחה — כמה הזמנות',
    default: 'ההזמנות נקלטו! הברקודים מחכים לך למעלה תחת "הסבבים שלי".',
    kind: 'long',
  },
  {
    key: 'customer.bookflow.successSingle',
    group: 'customer_bookflow',
    label: 'הצלחה — הזמנה אחת',
    default: 'ההזמנה נקלטה! הברקוד מחכה לך למעלה תחת "הסבבים שלי".',
    kind: 'long',
  },
  { key: 'customer.bookflow.emptyClosed', group: 'customer_bookflow', label: 'אין מועדים — סגור', default: 'המקום סגור בתאריך זה.', kind: 'short' },
  {
    key: 'customer.bookflow.emptyFreePlay',
    group: 'customer_bookflow',
    label: 'אין מועדים — כניסה חופשית',
    default: 'בתאריך זה הכניסה חופשית — אין צורך בהזמנת סבב, פשוט מגיעים.',
    kind: 'long',
  },
  { key: 'customer.bookflow.emptyNoRounds', group: 'customer_bookflow', label: 'אין מועדים — אין סבבים', default: 'אין סבבים פנויים ביום זה.', kind: 'short' },
  {
    key: 'customer.bookflow.emptyAllFull',
    group: 'customer_bookflow',
    label: 'אין מועדים — הכל מלא',
    default: 'כל הסבבים מלאים ביום זה — אפשר להצטרף לרשימת ההמתנה.',
    kind: 'long',
  },
  { key: 'customer.bookflow.allFullJoin', group: 'customer_bookflow', label: 'כותרת — הכל מלא', default: 'סבבים מלאים — אפשר להירשם לרשימת המתנה', kind: 'short' },
  { key: 'customer.bookflow.waitlist', group: 'customer_bookflow', label: 'כפתור — רשימת המתנה', default: 'רשימת המתנה', kind: 'short' },
  { key: 'customer.bookflow.howManyEntries', group: 'customer_bookflow', label: 'תווית — כמה כניסות', default: 'כמה כניסות?', kind: 'short' },
  {
    key: 'customer.bookflow.punchOne',
    group: 'customer_bookflow',
    label: 'סיכום — כניסה אחת',
    help: '{{time}} טווח הסבב, {{remaining}} כניסות שנותרו.',
    default: 'כניסה לסבב {{time}}. ינוקב כרטיס אחד מתוך {{remaining}} שנותרו.',
    kind: 'long',
    placeholders: ['time', 'remaining'],
  },
  {
    key: 'customer.bookflow.punchMany',
    group: 'customer_bookflow',
    label: 'סיכום — כמה כניסות',
    help: '{{count}} מספר הכניסות, {{time}} טווח הסבב, {{remaining}} כניסות שנותרו.',
    default: '{{count}} כניסות לסבב {{time}}. ינוקבו {{count}} כניסות מתוך {{remaining}} שנותרו.',
    kind: 'long',
    placeholders: ['count', 'time', 'remaining'],
  },
  { key: 'customer.bookflow.companionIncluded', group: 'customer_bookflow', label: 'הערה — מלווה כלול', default: 'מלווה אחד כלול בכל כניסה.', kind: 'short' },
  { key: 'customer.bookflow.extraCompanion', group: 'customer_bookflow', label: 'תווית — מלווה נוסף', default: 'מלווה נוסף', kind: 'short' },
  {
    key: 'customer.bookflow.extraCompanionNote',
    group: 'customer_bookflow',
    label: 'הערה — מלווה נוסף',
    default: 'מלווה אחד כלול בכניסה. התשלום מתבצע באתר בסיום ההזמנה.',
    kind: 'long',
  },
  {
    key: 'customer.bookflow.confirmPay',
    group: 'customer_bookflow',
    label: 'כפתור — אישור ותשלום',
    help: '{{price}} מחיר המלווה בשקלים.',
    default: 'אישור, הזמנה ותשלום ₪{{price}}',
    kind: 'short',
    placeholders: ['price'],
  },
  { key: 'customer.bookflow.confirm', group: 'customer_bookflow', label: 'כפתור — אישור והזמנה', default: 'אישור והזמנה', kind: 'short' },

  // ── אזור אישי — בחירת תאריך וסבב (DayStrip / MonthCalendar / …) ────
  { key: 'customer.picker.prevMonth', group: 'customer_picker', label: 'לוח שנה — חודש קודם', default: 'חודש קודם', kind: 'short' },
  { key: 'customer.picker.nextMonth', group: 'customer_picker', label: 'לוח שנה — חודש הבא', default: 'חודש הבא', kind: 'short' },
  { key: 'customer.picker.calendarTitle', group: 'customer_picker', label: 'לוח שנה — כותרת כפתור', default: 'בחירת תאריך מלוח שנה', kind: 'short' },
  { key: 'customer.picker.calendar', group: 'customer_picker', label: 'תווית — לוח שנה', default: 'לוח שנה', kind: 'short' },
  { key: 'customer.picker.today', group: 'customer_picker', label: 'תווית — היום', default: 'היום', kind: 'short' },
  { key: 'customer.picker.legendOk', group: 'customer_picker', label: 'מקרא — הרבה מקום', default: 'הרבה מקום', kind: 'short' },
  { key: 'customer.picker.legendWarn', group: 'customer_picker', label: 'מקרא — נשארו מעט', default: 'נשארו מעט', kind: 'short' },
  { key: 'customer.picker.legendFull', group: 'customer_picker', label: 'מקרא — מלא', default: 'מלא', kind: 'short' },
  { key: 'customer.picker.legendFree', group: 'customer_picker', label: 'מקרא — כניסה חופשית', default: 'כניסה חופשית', kind: 'short' },
  { key: 'customer.picker.legendClosed', group: 'customer_picker', label: 'מקרא — סגור', default: 'סגור', kind: 'short' },
  {
    key: 'customer.picker.available',
    group: 'customer_picker',
    label: 'סבב — מקומות פנויים',
    help: '{{count}} מספר המקומות הפנויים.',
    default: '{{count}} פנויים',
    kind: 'short',
    placeholders: ['count'],
  },

  // ── אזור אישי — רשימת המתנה (WaitlistEntryCard) ───────────────────
  { key: 'customer.waitlist.leaveError', group: 'customer_waitlist', label: 'שגיאה — יציאה מהרשימה', default: 'לא ניתן לצאת מהרשימה כרגע.', kind: 'long' },
  {
    key: 'customer.waitlist.claimAvailable',
    group: 'customer_waitlist',
    label: 'הודעה — התפנה מקום',
    help: '{{deadline}} טקסט הזמן (למשל " עד השעה 14:00") או ריק.',
    default: 'התפנה מקום! הזמינו כניסה{{deadline}} לפני שהמקום יעבור לבא/ה בתור.',
    kind: 'long',
    placeholders: ['deadline'],
  },
  {
    key: 'customer.waitlist.claimDeadline',
    group: 'customer_waitlist',
    label: 'הודעה — עד השעה',
    help: '{{time}} שעת התפיסה האחרונה.',
    default: 'עד השעה {{time}}',
    kind: 'short',
    placeholders: ['time'],
  },
  { key: 'customer.waitlist.waiting', group: 'customer_waitlist', label: 'הודעה — ממתין ברשימה', default: 'ממתינ/ה ברשימה. נודיע לך ברגע שיתפנה מקום.', kind: 'long' },
  { key: 'customer.waitlist.leave', group: 'customer_waitlist', label: 'כפתור — יציאה מהרשימה', default: 'יציאה מהרשימה', kind: 'short' },

  // ── אזור אישי — פרופיל (ProfileScreen / ProfileEdit) ──────────────
  { key: 'customer.profile.saved', group: 'customer_profile', label: 'הודעה — הפרטים נשמרו', default: 'הפרטים נשמרו', kind: 'short' },
  { key: 'customer.profile.editTitle', group: 'customer_profile', label: 'כותרת — עריכת פרטים', default: 'עריכת פרטים', kind: 'short' },
  { key: 'customer.profile.firstName', group: 'customer_profile', label: 'תווית — שם פרטי', default: 'שם פרטי', kind: 'short' },
  { key: 'customer.profile.lastName', group: 'customer_profile', label: 'תווית — שם משפחה', default: 'שם משפחה', kind: 'short' },
  { key: 'customer.profile.phone', group: 'customer_profile', label: 'תווית — טלפון', default: 'טלפון', kind: 'short' },
  { key: 'customer.profile.phoneLocked', group: 'customer_profile', label: 'הערה — טלפון נעול', default: 'לא ניתן לשנות טלפון · פנו לצוות', kind: 'short' },
  { key: 'customer.profile.email', group: 'customer_profile', label: 'תווית — מייל', default: 'מייל', kind: 'short' },
  { key: 'customer.profile.preferredChannel', group: 'customer_profile', label: 'תווית — ערוץ מועדף', default: 'ערוץ עדכונים מועדף', kind: 'short' },
  { key: 'customer.profile.channelSms', group: 'customer_profile', label: 'ערוץ — SMS', default: 'SMS', kind: 'short' },
  { key: 'customer.profile.channelWhatsapp', group: 'customer_profile', label: 'ערוץ — וואטסאפ', default: 'וואטסאפ', kind: 'short' },
  { key: 'customer.profile.channelEmail', group: 'customer_profile', label: 'ערוץ — מייל', default: 'מייל', kind: 'short' },
  { key: 'customer.profile.children', group: 'customer_profile', label: 'תווית — ילדים רשומים', default: 'ילדים רשומים', kind: 'short' },
  { key: 'customer.profile.childrenLocked', group: 'customer_profile', label: 'הערה — ילדים נעולים', default: 'לעריכת רשימת הילדים · פנו לצוות', kind: 'short' },
  { key: 'customer.profile.cancel', group: 'customer_profile', label: 'כפתור — ביטול', default: 'ביטול', kind: 'short' },
  { key: 'customer.profile.save', group: 'customer_profile', label: 'כפתור — שמירת שינויים', default: 'שמירת שינויים', kind: 'short' },
  { key: 'customer.profile.errRequired', group: 'customer_profile', label: 'שגיאה — שם חובה', default: 'שם פרטי ושם משפחה הם שדות חובה.', kind: 'long' },
  { key: 'customer.profile.errEmail', group: 'customer_profile', label: 'שגיאה — מייל לא תקין', default: 'כתובת מייל לא תקינה.', kind: 'short' },
  { key: 'customer.profile.errInvalidBody', group: 'customer_profile', label: 'שגיאה — שדה לא תקין', default: 'אחד השדות לא תקין.', kind: 'short' },
  { key: 'customer.profile.errNotFound', group: 'customer_profile', label: 'שגיאה — פרופיל לא נמצא', default: 'הפרופיל לא נמצא. רעננו את הדף.', kind: 'long' },
  { key: 'customer.profile.errGeneric', group: 'customer_profile', label: 'שגיאה — כללית', default: 'תקלה זמנית. נסו שוב בעוד רגע.', kind: 'long' },
];

/** key → default text, for the fail-safe fallback the apps bundle. */
export const contentDefaults: Record<string, string> = Object.fromEntries(
  CONTENT_REGISTRY.map((e) => [e.key, e.default]),
);

/** Every registered key, for O(1) validation of overrides and t() calls. */
export const contentKeys: ReadonlySet<string> = new Set(CONTENT_REGISTRY.map((e) => e.key));

const byKey: Map<string, ContentEntry> = new Map(CONTENT_REGISTRY.map((e) => [e.key, e]));

export function getContentEntry(key: string): ContentEntry | undefined {
  return byKey.get(key);
}

/** Entries in a group, in registry order — drives the grouped admin editor. */
export function contentEntriesByGroup(group: ContentGroup): ContentEntry[] {
  return CONTENT_REGISTRY.filter((e) => e.group === group);
}
