import assert from 'node:assert/strict';
import { beforeEach, test } from 'node:test';
import { PulseemProvider } from './pulseem-provider';

interface FetchCall {
  url: string;
  init: RequestInit;
}

let calls: FetchCall[] = [];
let responseQueue: { status: number; body?: unknown; text?: string }[] = [];

function makeFetch(): typeof fetch {
  return (async (input: unknown, init: RequestInit = {}) => {
    calls.push({ url: String(input), init });
    const next = responseQueue.shift();
    if (!next) {
      throw new Error(`[test] no more stubbed responses; got ${calls.length} calls`);
    }
    const body = next.text ?? (next.body === undefined ? '' : JSON.stringify(next.body));
    return new Response(body, {
      status: next.status,
      headers: body && next.body !== undefined ? { 'Content-Type': 'application/json' } : {},
    });
  }) as typeof fetch;
}

beforeEach(() => {
  calls = [];
  responseQueue = [];
});

function make(extra: { responses?: typeof responseQueue } = {}) {
  if (extra.responses) responseQueue = [...extra.responses];
  return new PulseemProvider({
    apiKey: 'pk-test-abc',
    fromNumber: 'MEMESH',
    fetchImpl: makeFetch(),
  });
}

test('constructor throws when apiKey is missing', () => {
  assert.throws(
    () => new PulseemProvider({ apiKey: '', fromNumber: 'MEMESH' }),
    /apiKey is required/,
  );
});

test('constructor throws when fromNumber is missing', () => {
  assert.throws(
    () => new PulseemProvider({ apiKey: 'k', fromNumber: '' }),
    /fromNumber.*required/,
  );
});

test('send POSTs to the documented endpoint with X-Api-Key header and JSON body', async () => {
  const p = make({ responses: [{ status: 200, body: { status: 0, id: 'srv-1' } }] });
  const res = await p.send({ to: '052-345-6789', body: 'hello' });

  assert.equal(res.ok, true);
  if (res.ok) assert.equal(res.id, 'srv-1');

  assert.equal(calls.length, 1);
  assert.equal(calls[0]?.init.method, 'POST');
  assert.equal(calls[0]?.url, 'https://api.pulseem.com/api/v1/SmsApi/SendSms');

  const headers = calls[0]?.init.headers as Record<string, string> | undefined;
  assert.equal(headers?.['X-Api-Key'], 'pk-test-abc');
  assert.equal(headers?.['Content-Type'], 'application/json');
  // Must NOT use Bearer auth — that's the 019 provider's pattern, not Pulseem's.
  assert.equal(headers?.['Authorization'], undefined);
});

test('send body shape: sendId + isAsync + smsSendData with parallel arrays', async () => {
  const p = make({ responses: [{ status: 200, body: { status: 0 } }] });
  await p.send({ to: '0523456789', body: 'קוד הכניסה: 482719' });
  const parsed = JSON.parse(String(calls[0]?.init.body)) as {
    sendId: string;
    isAsync: boolean;
    smsSendData: {
      fromNumber: string;
      toNumberList: string[];
      textList: string[];
    };
  };
  assert.equal(typeof parsed.sendId, 'string');
  assert.ok(parsed.sendId.length > 0, 'sendId is generated by the provider');
  assert.equal(parsed.isAsync, false);
  assert.equal(parsed.smsSendData.fromNumber, 'MEMESH');
  assert.deepEqual(parsed.smsSendData.toNumberList, ['0523456789']);
  assert.deepEqual(parsed.smsSendData.textList, ['קוד הכניסה: 482719']);
});

test('send normalizes the phone before posting (strips dashes, drops +972)', async () => {
  const p = make({ responses: [{ status: 200, body: { status: 0 } }] });
  await p.send({ to: '+972 52 345 6789', body: 'hi' });
  const parsed = JSON.parse(String(calls[0]?.init.body)) as {
    smsSendData: { toNumberList: string[] };
  };
  assert.equal(parsed.smsSendData.toNumberList[0], '0523456789');
});

test('send falls back to the generated sendId when the server omits id', async () => {
  const p = make({ responses: [{ status: 200, body: {} }] });
  const res = await p.send({ to: '0523456789', body: 'x' });
  assert.equal(res.ok, true);
  if (res.ok) {
    assert.equal(typeof res.id, 'string');
    // The generated sendId is a UUID — 36 chars including dashes.
    assert.match(res.id ?? '', /^[0-9a-f-]{36}$/);
  }
});

test('send returns ok:false on HTTP 4xx, preferring the server message', async () => {
  const p = make({
    responses: [{ status: 401, body: { message: 'invalid_api_key' } }],
  });
  const res = await p.send({ to: '0523456789', body: 'x' });
  assert.equal(res.ok, false);
  if (!res.ok) assert.equal(res.error, 'invalid_api_key');
});

test('send returns ok:false on HTTP 500 with a generic http_500 when body is empty', async () => {
  const p = make({ responses: [{ status: 500, text: '' }] });
  const res = await p.send({ to: '0523456789', body: 'x' });
  assert.equal(res.ok, false);
  if (!res.ok) assert.equal(res.error, 'http_500');
});

test('send returns ok:false with the normalized phone error when input is invalid', async () => {
  const p = make({ responses: [] });
  const res = await p.send({ to: '', body: 'x' });
  assert.equal(res.ok, false);
  assert.match(res.error ?? '', /phone is required/);
  // No HTTP call was made.
  assert.equal(calls.length, 0);
});

test('send uses a custom baseUrl when provided', async () => {
  const p = new PulseemProvider({
    apiKey: 'k',
    fromNumber: 'MEMESH',
    baseUrl: 'https://api.pulseem.com/staging',
    fetchImpl: makeFetch(),
  });
  responseQueue = [{ status: 200, body: { status: 0 } }];
  await p.send({ to: '0523456789', body: 'x' });
  assert.equal(calls[0]?.url, 'https://api.pulseem.com/staging/api/v1/SmsApi/SendSms');
});
