import assert from 'node:assert/strict';
import { beforeEach, test } from 'node:test';
import { PulseemProvider } from './pulseem-provider';

interface FetchCall {
  url: string;
  init: RequestInit;
}

let calls: FetchCall[] = [];
let responseQueue: { status: number; body?: unknown; text?: string }[] = [];

function makeFetch(): typeof fetch {
  return (async (input: unknown, init: RequestInit = {}) => {
    calls.push({ url: String(input), init });
    const next = responseQueue.shift();
    if (!next) {
      throw new Error(`[test] no more stubbed responses; got ${calls.length} calls`);
    }
    const body = next.text ?? (next.body === undefined ? '' : JSON.stringify(next.body));
    return new Response(body, {
      status: next.status,
      headers: body && next.body !== undefined ? { 'Content-Type': 'application/json' } : {},
    });
  }) as typeof fetch;
}

beforeEach(() => {
  calls = [];
  responseQueue = [];
});

function make(extra: { responses?: typeof responseQueue } = {}) {
  if (extra.responses) responseQueue = [...extra.responses];
  return new PulseemProvider({
    apiKey: 'pk-test-abc',
    fromNumber: 'MEMESH',
    fetchImpl: makeFetch(),
  });
}

test('constructor throws when apiKey is missing', () => {
  assert.throws(
    () => new PulseemProvider({ apiKey: '', fromNumber: 'MEMESH' }),
    /apiKey is required/,
  );
});

test('constructor throws when fromNumber is missing', () => {
  assert.throws(
    () => new PulseemProvider({ apiKey: 'k', fromNumber: '' }),
    /fromNumber.*required/,
  );
});

test('send POSTs to the documented endpoint with APIKEY header and JSON body', async () => {
  const p = make({
    responses: [{ status: 200, body: { status: 'Success', success: 1, sessionId: 'sess-1' } }],
  });
  const res = await p.send({ to: '052-345-6789', body: 'hello' });

  assert.equal(res.ok, true);
  if (res.ok) assert.equal(res.id, 'sess-1');

  assert.equal(calls.length, 1);
  assert.equal(calls[0]?.init.method, 'POST');
  assert.equal(calls[0]?.url, 'https://api.pulseem.com/api/v1/SmsApi/SendSms');

  const headers = calls[0]?.init.headers as Record<string, string> | undefined;
  // Pulseem's server expects the literal header name "APIKEY", not the
  // swagger-documented "X-Api-Key". Anything else produces a 403
  // "Invalid API Key!" response.
  assert.equal(headers?.['APIKEY'], 'pk-test-abc');
  assert.equal(headers?.['X-Api-Key'], undefined);
  assert.equal(headers?.['Content-Type'], 'application/json');
  // Must NOT use Bearer auth — that's the 019 provider's pattern, not Pulseem's.
  assert.equal(headers?.['Authorization'], undefined);
});

test('send body shape: sendId + smsSendData with parallel arrays + referenceList; NO isAsync', async () => {
  const p = make({ responses: [{ status: 200, body: { status: 'Success', success: 1 } }] });
  await p.send({ to: '0523456789', body: 'קוד הכניסה: 482719' });
  const parsed = JSON.parse(String(calls[0]?.init.body)) as Record<string, unknown> & {
    sendId: string;
    smsSendData: {
      fromNumber: string;
      toNumberList: string[];
      textList: string[];
      referenceList: string[];
    };
  };
  assert.equal(typeof parsed.sendId, 'string');
  assert.ok(parsed.sendId.length > 0, 'sendId is generated by the provider');
  // CRITICAL: isAsync must NOT be present. Pulseem's server returns HTTP 500
  // with body "Error" when it is, regardless of fromNumber.
  assert.equal('isAsync' in parsed, false, 'isAsync must not appear in the request body');
  assert.equal(parsed.smsSendData.fromNumber, 'MEMESH');
  assert.deepEqual(parsed.smsSendData.toNumberList, ['0523456789']);
  assert.deepEqual(parsed.smsSendData.textList, ['קוד הכניסה: 482719']);
  // referenceList must be a parallel array (one entry per recipient).
  assert.equal(parsed.smsSendData.referenceList.length, 1);
  assert.match(parsed.smsSendData.referenceList[0] ?? '', /^[0-9a-f-]{36}$/);
});

test('send treats HTTP 200 + status:"Error" as a failure (Pulseem app-level error)', async () => {
  // The exact response Pulseem returns for an unauthorized English fromNumber.
  // Our pre-2026-06-21 code interpreted HTTP 200 as success and silently
  // dropped the SMS without an error trail.
  const p = make({
    responses: [
      {
        status: 200,
        body: {
          sendId: 'srv-xyz',
          status: 'Error',
          error: "English letter are not allowed in 'FromNumber' for this account , Please contact support to verify your account",
          count: 0,
          success: 0,
          failure: 0,
          items: [],
        },
      },
    ],
  });
  const res = await p.send({ to: '0523456789', body: 'x' });
  assert.equal(res.ok, false);
  if (!res.ok) {
    assert.match(res.error ?? '', /English letter/);
  }
});

test('send treats HTTP 200 + status:"Success" + sessionId as success and surfaces sessionId as the id', async () => {
  const p = make({
    responses: [
      {
        status: 200,
        body: {
          sendId: 'req-abc',
          status: 'Success',
          success: 1,
          failure: 0,
          sessionId: 'sess-123',
          items: [{ toNumber: '0523456789', reference: 'ref-1', message: 'SUCCESS' }],
        },
      },
    ],
  });
  const res = await p.send({ to: '0523456789', body: 'x' });
  assert.equal(res.ok, true);
  if (res.ok) assert.equal(res.id, 'sess-123');
});

test('send normalizes the phone before posting (strips dashes, drops +972)', async () => {
  const p = make({ responses: [{ status: 200, body: { status: 0 } }] });
  await p.send({ to: '+972 52 345 6789', body: 'hi' });
  const parsed = JSON.parse(String(calls[0]?.init.body)) as {
    smsSendData: { toNumberList: string[] };
  };
  assert.equal(parsed.smsSendData.toNumberList[0], '0523456789');
});

test('send falls back to the generated sendId when 2xx body is empty/missing structure', async () => {
  // text:'' simulates a 200 with no parseable body — `parsed` is undefined
  // so the app-level status check is skipped and the request is treated as
  // success with the locally-generated sendId.
  const p = make({ responses: [{ status: 200, text: '' }] });
  const res = await p.send({ to: '0523456789', body: 'x' });
  assert.equal(res.ok, true);
  if (res.ok) {
    assert.equal(typeof res.id, 'string');
    // The generated sendId is a UUID — 36 chars including dashes.
    assert.match(res.id ?? '', /^[0-9a-f-]{36}$/);
  }
});

test('send returns ok:false on HTTP 4xx, preferring the server error field', async () => {
  const p = make({
    responses: [{ status: 401, body: { error: 'invalid_api_key' } }],
  });
  const res = await p.send({ to: '0523456789', body: 'x' });
  assert.equal(res.ok, false);
  if (!res.ok) assert.equal(res.error, 'invalid_api_key');
});

test('send returns ok:false on HTTP 500 with a generic http_500 when body is empty', async () => {
  const p = make({ responses: [{ status: 500, text: '' }] });
  const res = await p.send({ to: '0523456789', body: 'x' });
  assert.equal(res.ok, false);
  if (!res.ok) assert.equal(res.error, 'http_500');
});

test('send returns ok:false with the normalized phone error when input is invalid', async () => {
  const p = make({ responses: [] });
  const res = await p.send({ to: '', body: 'x' });
  assert.equal(res.ok, false);
  assert.match(res.error ?? '', /phone is required/);
  // No HTTP call was made.
  assert.equal(calls.length, 0);
});

test('send uses a custom baseUrl when provided', async () => {
  const p = new PulseemProvider({
    apiKey: 'k',
    fromNumber: 'MEMESH',
    baseUrl: 'https://api.pulseem.com/staging',
    fetchImpl: makeFetch(),
  });
  responseQueue = [{ status: 200, body: { status: 0 } }];
  await p.send({ to: '0523456789', body: 'x' });
  assert.equal(calls[0]?.url, 'https://api.pulseem.com/staging/api/v1/SmsApi/SendSms');
});
