CREATE TABLE "role_permissions" (
	"role" "staff_role" NOT NULL,
	"permission" varchar(64) NOT NULL,
	"granted" boolean DEFAULT false NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" uuid,
	CONSTRAINT "role_permissions_role_permission_pk" PRIMARY KEY("role","permission")
);
--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_updated_by_staff_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."staff"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
-- Seed defaults from packages/db/src/permissions-catalog.ts. ON CONFLICT DO
-- NOTHING so re-running the migration after an admin has hand-edited a row
-- never clobbers the live configuration. Future permissions need their own
-- follow-up migration that appends INSERTs for the new keys.
INSERT INTO "role_permissions" ("role", "permission", "granted") VALUES
  ('admin',   'staff.view',                 true),
  ('manager', 'staff.view',                 true),
  ('cashier', 'staff.view',                 false),
  ('admin',   'staff.create',               true),
  ('manager', 'staff.create',               false),
  ('cashier', 'staff.create',               false),
  ('admin',   'staff.edit',                 true),
  ('manager', 'staff.edit',                 false),
  ('cashier', 'staff.edit',                 false),
  ('admin',   'staff.delete',               true),
  ('manager', 'staff.delete',               false),
  ('cashier', 'staff.delete',               false),
  ('admin',   'staff.change_role',          true),
  ('manager', 'staff.change_role',          false),
  ('cashier', 'staff.change_role',          false),
  ('admin',   'staff.deactivate',           true),
  ('manager', 'staff.deactivate',           false),
  ('cashier', 'staff.deactivate',           false),
  ('admin',   'staff.manage_pin',           true),
  ('manager', 'staff.manage_pin',           true),
  ('cashier', 'staff.manage_pin',           false),
  ('admin',   'staff.reset_password',       true),
  ('manager', 'staff.reset_password',       false),
  ('cashier', 'staff.reset_password',       false),
  ('admin',   'staff.manage_permissions',   true),
  ('manager', 'staff.manage_permissions',   false),
  ('cashier', 'staff.manage_permissions',   false),
  ('admin',   'customers.view',             true),
  ('manager', 'customers.view',             true),
  ('cashier', 'customers.view',             true),
  ('admin',   'customers.view_contact',     true),
  ('manager', 'customers.view_contact',     true),
  ('cashier', 'customers.view_contact',     true),
  ('admin',   'customers.create',           true),
  ('manager', 'customers.create',           true),
  ('cashier', 'customers.create',           true),
  ('admin',   'customers.edit',             true),
  ('manager', 'customers.edit',             true),
  ('cashier', 'customers.edit',             false),
  ('admin',   'customers.delete',           true),
  ('manager', 'customers.delete',           false),
  ('cashier', 'customers.delete',           false),
  ('admin',   'cards.view',                 true),
  ('manager', 'cards.view',                 true),
  ('cashier', 'cards.view',                 true),
  ('admin',   'cards.create',               true),
  ('manager', 'cards.create',               true),
  ('cashier', 'cards.create',               true),
  ('admin',   'cards.edit',                 true),
  ('manager', 'cards.edit',                 true),
  ('cashier', 'cards.edit',                 false),
  ('admin',   'cards.cancel',               true),
  ('manager', 'cards.cancel',               true),
  ('cashier', 'cards.cancel',               false),
  ('admin',   'cards.reassign',             true),
  ('manager', 'cards.reassign',             true),
  ('cashier', 'cards.reassign',             false),
  ('admin',   'cards.refund_entry',         true),
  ('manager', 'cards.refund_entry',         true),
  ('cashier', 'cards.refund_entry',         false),
  ('admin',   'punches.create',             true),
  ('manager', 'punches.create',             true),
  ('cashier', 'punches.create',             true),
  ('admin',   'punches.reverse',            true),
  ('manager', 'punches.reverse',            true),
  ('cashier', 'punches.reverse',            false),
  ('admin',   'reports.view_basic',         true),
  ('manager', 'reports.view_basic',         true),
  ('cashier', 'reports.view_basic',         false),
  ('admin',   'reports.view_financial',     true),
  ('manager', 'reports.view_financial',     false),
  ('cashier', 'reports.view_financial',     false),
  ('admin',   'reports.export',             true),
  ('manager', 'reports.export',             true),
  ('cashier', 'reports.export',             false),
  ('admin',   'settings.view',              true),
  ('manager', 'settings.view',              false),
  ('cashier', 'settings.view',              false),
  ('admin',   'settings.edit_card_settings',true),
  ('manager', 'settings.edit_card_settings',false),
  ('cashier', 'settings.edit_card_settings',false),
  ('admin',   'settings.edit_brand',        true),
  ('manager', 'settings.edit_brand',        false),
  ('cashier', 'settings.edit_brand',        false),
  ('admin',   'settings.edit_integrations', true),
  ('manager', 'settings.edit_integrations', false),
  ('cashier', 'settings.edit_integrations', false),
  ('admin',   'audit.view',                 true),
  ('manager', 'audit.view',                 true),
  ('cashier', 'audit.view',                 false)
ON CONFLICT ("role", "permission") DO NOTHING;